cxx = cl.exe
cxxflags = -nologo -W3 -O2 -D_UNICODE

all: mkshortcut.exe shortcutinfo.exe

clean:
	del mkshortcut.exe shortcutinfo.exe

mkshortcut.exe:
	$(cxx) $(cxxflags) mkshortcut.cpp

shortcutinfo.exe:
	$(cxx) $(cxxflags) shortcutinfo.cpp

